This file was tested with MacOS using Conda for Python management.

Make sure that your Python env has `pandas` and `sqlalchemy` installed. I also had to install `psycopg2` manually.

In [12]:
import pandas as pd
pd.__version__

'2.2.3'

The CSV file is very big and Pandas may not be able to handle it properly if the whole thing doesn't fit in RAM. We will only import 100 rows for now.

In [14]:
data = pd.read_parquet('yellow_cab_trip_data_jan_2021.parquet')

data.to_csv('yellow_cab_trip_data_jan_2021.csv')

In [15]:
df = pd.read_csv('yellow_cab_trip_data_jan_2021.csv', nrows=100)
df

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,2,2021-01-01 00:12:41,2021-01-01 00:26:47,1.0,4.13,1.0,N,161,226,1,14.5,0.5,0.5,3.66,0.0,0.3,21.96,2.5,NaN
96,96,2,2021-01-01 00:23:29,2021-01-01 00:35:03,2.0,4.12,1.0,N,162,74,2,13.5,0.5,0.5,0.00,0.0,0.3,17.30,2.5,NaN
97,97,2,2021-01-01 00:46:17,2021-01-01 00:54:25,2.0,2.22,1.0,N,144,170,1,9.0,0.5,0.5,2.56,0.0,0.3,15.36,2.5,NaN
98,98,2,2021-01-01 00:28:16,2021-01-01 00:51:44,1.0,7.11,1.0,N,264,264,2,23.5,0.5,0.5,0.00,0.0,0.3,24.80,0.0,NaN
99,99,2,2021-01-01 00:42:35,2021-01-01 00:54:41,3.0,1.61,1.0,N,229,237,2,9.5,0.5,0.5,0.00,0.0,0.3,13.30,2.5,NaN

We will now create the ***schema*** for the database. The _schema_ is the structure of the database; in this case it describes the columns of our table. Pandas can output the SQL ***DDL*** (Data definition language) instructions necessary to create the schema.

In [16]:
# We need to provide a name for the table; we will use 'yellow_taxi_data'
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"Unnamed: 0" INTEGER,
  "VendorID" INTEGER,
  "tpep_pickup_datetime" TEXT,
  "tpep_dropoff_datetime" TEXT,
  "passenger_count" REAL,
  "trip_distance" REAL,
  "RatecodeID" REAL,
  "store_and_fwd_flag" TEXT,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL,
  "airport_fee" REAL
)

Note that this only outputs the instructions, it hasn't actually created the table in the database yet.

Note that `tpep_pickup_datetime` and `tpep_dropoff_datetime` are text fields even though they should be timestamps. Let's change that.

In [17]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"Unnamed: 0" INTEGER,
  "VendorID" INTEGER,
  "tpep_pickup_datetime" TIMESTAMP,
  "tpep_dropoff_datetime" TIMESTAMP,
  "passenger_count" REAL,
  "trip_distance" REAL,
  "RatecodeID" REAL,
  "store_and_fwd_flag" TEXT,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL,
  "airport_fee" REAL
)

Even though we have the DDL instructions, we still need specific instructions for Postgres to connect to it and create the table. We will use `sqlalchemy` for this.

In [18]:
from sqlalchemy import create_engine

An ***engine*** specifies the database details in a URI. The structure of the URI is:

`database://user:password@host:port/database_name`

In [19]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [20]:
# run this cell when the Postgres Docker container is running
engine.connect()

In [21]:
# we can now use our engine to get the specific output for Postgres
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"Unnamed: 0" BIGINT,
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	"RatecodeID" FLOAT(53),
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53),
	airport_fee FLOAT(53)
)

We will now create an ***iterator*** that will allow us to read the CSV file in chunks and send them to the database. Otherwise, we may run into problems trying to send too much data at once.

In [22]:
df_iter = pd.read_csv('yellow_cab_trip_data_jan_2021.csv', iterator=True, chunksize=1000)

We can use the `next()` function to get the chunks using the iterator.

In [23]:
df = next(df_iter)
df

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,1,2021-01-01 00:57:42,2021-01-01 01:08:18,1.0,3.10,1.0,N,264,264,1,11.5,0.5,0.5,1.00,0.0,0.3,13.80,0.0,NaN
996,996,2,2021-01-01 00:19:34,2021-01-01 00:31:34,1.0,2.77,1.0,N,170,239,1,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,NaN
997,997,2,2021-01-01 00:16:38,2021-01-01 00:24:23,3.0,2.01,1.0,N,41,263,1,8.5,0.5,0.5,2.46,0.0,0.3,14.76,2.5,NaN
998,998,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1.0,3.35,1.0,N,263,186,4,-12.0,-0.5,-0.5,0.00,0.0,-0.3,-15.80,-2.5,NaN
999,999,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1.0,3.35,1.0,N,263,186,2,12.0,0.5,0.5,0.00,0.0,0.3,15.80,2.5,NaN


This is a brand new dataframe, so we need to convert the time columns to timestamp format.

In [24]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
df

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5,NaN
1,1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0,NaN
2,2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0,NaN
3,3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0,NaN
4,4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,1,2021-01-01 00:57:42,2021-01-01 01:08:18,1.0,3.10,1.0,N,264,264,1,11.5,0.5,0.5,1.00,0.0,0.3,13.80,0.0,NaN
996,996,2,2021-01-01 00:19:34,2021-01-01 00:31:34,1.0,2.77,1.0,N,170,239,1,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,NaN
997,997,2,2021-01-01 00:16:38,2021-01-01 00:24:23,3.0,2.01,1.0,N,41,263,1,8.5,0.5,0.5,2.46,0.0,0.3,14.76,2.5,NaN
998,998,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1.0,3.35,1.0,N,263,186,4,-12.0,-0.5,-0.5,0.00,0.0,-0.3,-15.80,-2.5,NaN
999,999,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1.0,3.35,1.0,N,263,186,2,12.0,0.5,0.5,0.00,0.0,0.3,15.80,2.5,NaN

We will now finally create the table in the database. With `df.head(n=0)` we can get the name of the columns only, without any additional data. We will use it to generate a SQL instruction to generate the table.

In [25]:
# we need to provide the table name, the connection and what to do if the table already exists
# we choose to replace everything in case you had already created something by accident before.
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

You can now use `pgcli -h localhost -p 5432 -u root -d ny_taxi` on a separate terminal to look at the database:

* `\dt` for looking at available tables.
* `\d yellow_taxi_data` for describing the new table.

Let's include our current chunk to our database and time how long it takes.

In [26]:
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

CPU times: user 139 ms, sys: 3.15 ms, total: 142 ms
Wall time: 313 ms

1000

Back on the terminal running `pgcli`, we can check how many lines were to the database with:

```sql
SELECT count(1) FROM yellow_taxi_data;
```

You should see 100,000 lines.

Let's write a loop to write all chunks to the database. Use the terminal with `pgcli` to check the database after the code finishes running.

In [27]:
from time import time

while True: 
    try:
        t_start = time()
        df = next(df_iter)

        df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
        df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
        
        df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

        t_end = time()

        print('inserted another chunk, took %.3f second' % (t_end - t_start))
    except StopIteration:
        print('completed')
        break

inserted another chunk, took 0.381 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.294 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.246 second
inserted another chunk, took 0.236 second
inserted another chunk, took 0.218 second
inserted another chunk, took 0.252 second
inserted another chunk, took 0.354 second
inserted another chunk, took 0.327 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.253 second
inserted another chunk, took 0.204 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.444 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.295 second
inserted another chunk, took 0.201 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.319 second
inserted another chunk, took 0.176 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.221 second
inserted another chunk, took 0.267 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.178 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.240 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.175 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.219 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.199 second
inserted another chunk, took 0.155 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.287 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.198 second
inserted another chunk, took 0.163 second
inserted another chunk, took 0.243 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.229 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.196 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.205 second
inserted another chunk, took 0.217 second
inserted another chunk, took 0.244 second
inserted another chunk, took 0.203 second
inserted another chunk, took 0.301 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.353 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.377 second
inserted another chunk, took 0.226 second
inserted another chunk, took 0.316 second
inserted another chunk, took 0.183 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.286 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.199 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.310 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.204 second
inserted another chunk, took 0.175 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.254 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.293 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.175 second
inserted another chunk, took 0.164 second
inserted another chunk, took 0.310 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.178 second
inserted another chunk, took 0.159 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.182 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.302 second
inserted another chunk, took 0.335 second
inserted another chunk, took 0.278 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.245 second
inserted another chunk, took 0.294 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.180 second
inserted another chunk, took 0.226 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second

/tmp/ipykernel_219837/74935928.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

inserted another chunk, took 0.207 second
inserted another chunk, took 0.244 second
inserted another chunk, took 0.252 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.198 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.309 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.150 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.252 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.277 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.260 second
inserted another chunk, took 0.167 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.229 second
inserted another chunk, took 0.269 second
inserted another chunk, took 0.235 second
inserted another chunk, took 0.254 second
inserted another chunk, took 0.219 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.299 second
inserted another chunk, took 0.156 second
inserted another chunk, took 0.377 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.262 second
inserted another chunk, took 0.284 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.180 second
inserted another chunk, took 0.157 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.219 second
inserted another chunk, took 0.158 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.344 second
inserted another chunk, took 0.204 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.279 second
inserted another chunk, took 0.251 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.174 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.178 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.324 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.235 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.193 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.256 second
inserted another chunk, took 0.157 second
inserted another chunk, took 0.220 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.377 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.188 second
inserted another chunk, took 0.191 second
inserted another chunk, took 0.163 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.206 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.302 second
inserted another chunk, took 0.236 second
inserted another chunk, took 0.235 second
inserted another chunk, took 0.254 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.188 second
inserted another chunk, took 0.209 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.361 second
inserted another chunk, took 0.238 second
inserted another chunk, took 0.167 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.192 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.217 second
inserted another chunk, took 0.164 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.151 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.186 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.175 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.204 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.436 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.145 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.271 second
inserted another chunk, took 0.160 second

/tmp/ipykernel_219837/74935928.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

inserted another chunk, took 0.152 second
inserted another chunk, took 0.238 second
inserted another chunk, took 0.191 second
inserted another chunk, took 0.229 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.236 second
inserted another chunk, took 0.252 second
inserted another chunk, took 0.172 second
inserted another chunk, took 0.196 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.193 second
inserted another chunk, took 0.147 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.245 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.181 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.219 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.218 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.535 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.203 second
inserted another chunk, took 0.176 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.159 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.238 second
inserted another chunk, took 0.166 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.295 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.277 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.180 second
inserted another chunk, took 0.167 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.204 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.143 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.237 second
inserted another chunk, took 0.422 second
inserted another chunk, took 0.173 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.238 second
inserted another chunk, took 0.191 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.192 second
inserted another chunk, took 0.174 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.435 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.260 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.157 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.193 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.178 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.210 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.173 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.144 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.194 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.202 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.166 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.322 second
inserted another chunk, took 0.157 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.277 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.363 second
inserted another chunk, took 0.159 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.187 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.171 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.229 second
inserted another chunk, took 0.252 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.166 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.279 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.560 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.185 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.212 second
inserted another chunk, took 0.220 second
inserted another chunk, took 0.159 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.154 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.170 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.292 second
inserted another chunk, took 0.192 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.337 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.173 second
inserted another chunk, took 0.166 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.219 second
inserted another chunk, took 0.227 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.248 second
inserted another chunk, took 0.165 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.162 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.177 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.195 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.169 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.161 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.153 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.193 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.160 second
inserted another chunk, took 0.179 second
inserted another chunk, took 0.152 second
inserted another chunk, took 0.168 second
inserted another chunk, took 0.211 second
inserted another chunk, took 0.161 second

And that's it! Feel free to go back to the [notes](../notes/1_intro.md#inserting-data-to-postgres-with-python)